config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  devise_for :users, :controllers => { :registrations => :registrations }
  get '/users/me'
  resources :users do
    resources :interviews, :except => :show do
      collection do
        post 'send_request'
      end
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interview.rb
class Interview < ApplicationRecord
  belongs_to :user 
  enum status: { pending: 0, accepted: 1, rejected: 2 }
  validates :user_id, uniqueness: { scope: [:scheduled_datetime] }

  def committed?
    !pending?
  end

  def future?
    scheduled_datetime.future?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  enum gender: { male: 0, female: 1 }
  has_many :interviews, dependent: :destroy

  def age
    (Date.today.to_s(:number).to_i - birth_day.to_s(:number).to_i) / 10000
  end

  def accepted_interview
    interviews.find_by(status: :accepted)
  end

  def reject_interviews_except(excepted_interview)
    interviews.each do |interview|
      unless interview == excepted_interview
        interview.update(status: :rejected)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:user_name, :email, :birth_day, :gender, :school_name, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:index, :update]
  helper_method :current_user?

  def index
    @interviews = if current_user?(@user)
                    @user.interviews.order(:scheduled_datetime)
                  else
                    @user.interviews.where(status: :pending).or(@user.interviews.where(status: :rejected)).order(:scheduled_datetime)
                  end
    @users = User.where.not(id: current_user.id)
  end

  def show
  end

  def new
    @interview = current_user.interviews.build
  end

  def edit
  end

  def create
    @interview = current_user.interviews.build(interview_params)

    if @interview.save
      redirect_to user_interviews_path(current_user.id), notice: 'Interview was successfully created.'
    else
      render :new
    end
  end

  def update
    if @interview.update(interview_params)
      redirect_to user_interviews_path(params[:user_id]), notice: 'Interview was successfully updated.'
      unless current_user?(@user)
        @user.reject_interviews_except(@interview)
        InterviewMailer.approve(applicant: @user, interviewer: current_user).deliver_now
      end
    else
      render :edit
    end
  end

  def destroy
    @interview.destroy
    redirect_to user_interviews_path(current_user.id), notice: 'Interview was successfully destroyed.'
  end

  def send_request
    InterviewMailer.request_to(interviewer: User.find(params[:user]), from: current_user).deliver_now
    redirect_to user_interviews_path(current_user.id), notice: 'Request was successfully sent.'
  end

  def current_user?(user)
    current_user.id == user.id
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview
      @interview = Interview.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interview_params
      params.require(:interview).permit(:scheduled_datetime, :status)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_update_path_for(resource)
    users_me_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where.not(id: current_user.id)
  end

  def me
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/interviews/_form.html.erb
<%= form_with(model: interview, url: path, local: true) do |form| %>
  <% if interview.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(interview.errors.count, "error") %> prohibited this interview from being saved:</h2>

      <ul>
      <% interview.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4><%= title %> Interview</h4>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <%= form.label "Datetime" %><br />
        <%= form.datetime_select :scheduled_datetime, { id: :interview_scheduled_datetime,
        start_year: Time.now.year, end_year: Time.now.next_year.year },
        { class: "form-control auto-width inline-block" } %>
      </div>
    </div>
  </div>
  <%= form.submit btn_title, class: "btn btn-primary" %>
  <%= link_to 'Back', user_interviews_path(current_user.id), class: "btn btn-default" %>
<% end %>

app/views/interviews/_index_for_interviewer.html.erb
<h1><%= user.user_name %>'s Interviews</h1>
<h2>Current interview datetime: <%= user.accepted_interview ? user.accepted_interview.scheduled_datetime : '-' %></h2>
<p><%= interviews.empty? ? "There is no proposed datetime of interview." : "Select an interview datetime."%></p>
<div class="list-group">
  <% interviews.each do |interview| %>
    <% if interview.future? %>
      <%= link_to interview.scheduled_datetime, user_interview_path(user.id, interview.id, params: { interview: { status: :accepted } }),
      method: 'put', data: { confirm: "#{interview.scheduled_datetime} is selected.\nAre you sure?" }, class: "list-group-item" %>
    <% else %>
      <li class="list-group-item disabled"><%= interview.scheduled_datetime %></li>
    <% end %>
  <% end %>
</div>

app/views/interviews/_index_for_me.html.erb
<h1>My Interviews</h1>
<div class="container">
  <div class="row">
    <div class="col-lg-8">
      <%= link_to 'New Interview', new_user_interview_path, class: "btn btn-default" %>
    </div>
    <div class="col-lg-4">
    <%= form_with(url: send_request_user_interviews_path, local: true) do |form| %>
      <div style="display:inline-flex">
        <%= form.select :user, users.map { |user| [user.email, user.id] }, {}, { class: "form-control selectpicker show-tick" } %>
        <%= form.submit "Request", data: { confirm: "Do you send a approval request email?" },  class: "btn btn-success" %>
      </div>
    <% end %>
    </div>
  </div>
</div>
<br>
<div class="panel panel-default">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Datetime</th>
        <th>Status</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% interviews.each do |interview| %>
        <tr class=<%= interview.status == 'accepted' ? "success" : "" %>>
          <td><%= interview.scheduled_datetime %></td>
          <td><%= interview.status.capitalize %></td>
          <% button_state = interview.committed? ? "disabled" : "active" %>
          <td><%= link_to 'Edit', edit_user_interview_path(current_user.id, interview), class: "btn btn-primary #{button_state}" %></td>
          <td><%= link_to 'Remove', user_interview_path(current_user.id, interview),
          method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger #{button_state}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/interviews/edit.html.erb
<%= render 'form', { interview: @interview, path: user_interview_path, title: "Edit", btn_title: "Update" } %>

app/views/interviews/index.html.erb
<% if current_user?(@user) %>
  <%= render 'index_for_me', { interviews: @interviews, users: @users } %>
<% else %>
  <%= render 'index_for_interviewer', { interviews: @interviews, user: @user } %>
<% end %>

app/views/interviews/new.html.erb
<%= render 'form', { interview: @interview, path: user_interviews_path, title: "Create", btn_title: "Create" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ENavigator</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "ENavigator", root_path, id: "logo" %>
        <nav>
          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to 'Home', root_path %></li>
              <li><%= link_to 'Interviews', user_interviews_path(current_user.id) %></li>
              <li><%= link_to 'Profile', users_me_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            </ul>
          <% end %>
        </nav>
      </div>
    </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>

<div class="panel panel-default">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Age</th>
        <th>Gender</th>
        <th>School Name</th>
        <th>Interview Datetime</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td nowrap><%= user.user_name %></td>
          <td nowrap><%= user.email %></td>
          <td><%= user.age %></td>
          <td><%= user.gender.capitalize %></td>
          <td><%= user.school_name %></td>
          <td nowrap><%= user.accepted_interview.try(:scheduled_datetime) %></td>
          <td><%= link_to 'Show Interviews', user_interviews_path(user.id), class: "btn btn-primary" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/me.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>Profile</h4>
  </div>
  <div class="panel-body">
    <ul class="list-group">
      <li class="list-group-item">
        <div class="row">
          <div class="col-lg-2"><strong>Name: </strong></div>
          <div class="col-lg-4"><%= current_user.user_name %><div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="row">
          <div class="col-lg-2"><strong>Email: </strong></div>
          <div class="col-lg-4"><%= current_user.email %></div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="row">
          <div class="col-lg-2"><strong>Birth Day: </strong></div>
          <div class="col-lg-4"><%= current_user.birth_day %></div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="row">
          <div class="col-lg-2"><strong>Gender: </strong></div>
          <div class="col-lg-4"><%= current_user.gender.capitalize %></div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="row">
          <div class="col-lg-2"><strong>School Name: </strong></div>
          <div class="col-lg-4"><%= current_user.school_name %></div>
        </div>
      </li>
    </ul>
    <div>
      <%= link_to 'Edit', edit_user_registration_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>